var paciente = document.querySelector('#primeiro-paciente')

//Paulo

var HTML = paciente.querySelector('.info-peso')
var NotaHTML = HTML.textContent
console.log(peso)


var CSS = paciente.querySelector('.info-altura')
var NotaCSS = CSS.textContent
console.log(altura)

var JavaScript = paciente.querySelector('.info-gordura')
var NotaJavaScript = parseInt(JavaScript.textContent)
console.log(gordura)

var Media = paciente.querySelector('.info-imc')
var NotaMedia = Media.textContent
console.log(imc)

var valorIMC = parseInt(peso / altura*2)
console.log (valorIMC)

//João
var paciente = document.querySelector('#João')
var HTML = paciente.querySelector('.info-peso')
var NotaHTML = HTML.textContent

var CSS = paciente.querySelector('.info-altura')
var NotaCSS = CSS.textContent

var JavaScript = paciente.querySelector('.info-gordura')
var NotaJavaScript = JavaScript.textContent

var Media = paciente.querySelector('.info-imc')
var NotaMedia = Media.textContent

var valorIMC = parseInt(peso / altura*2)
console.log (valorIMC)


//Erica
var paciente = document.querySelector('#Erica')
var HTML = paciente.querySelector('.info-peso')
var NotaHTML = HTML.textContent

var CSS = paciente.querySelector('.info-altura')
var NotaCSS = CSS.textContent

var JavaScript = paciente.querySelector('.info-gordura')
var NotaJavaScript = JavaScript.textContent

var Media = paciente.querySelector('.info-imc')
var NotaMedia = Media.textContent

var valorIMC = parseInt(peso / altura*2)
console.log (valorIMC)


//Douglas
var paciente = document.querySelector('#Douglas')
var HTML = paciente.querySelector('.info-peso')
var NotaHTML = HTML.textContent

var CSS = paciente.querySelector('.info-altura')
var NotaCSS = CSS.textContent

var JavaScript = paciente.querySelector('.info-gordura')
var NotaJavaScript = JavaScript.textContent

var Media = paciente.querySelector('.info-imc')
var NotaMedia = Media.textContent

var valorIMC = parseInt(peso / altura*2)
console.log (valorIMC)

//Tatiana
var paciente = document.querySelector('#Tatiana')
var HTML = paciente.querySelector('.info-peso')
var NotaHTML = HTML.textContent

var CSS = paciente.querySelector('.info-altura')
var NotaCSS = CSS.textContent

var JavaScript = paciente.querySelector('.info-gordura')
var NotaJavaScript = JavaScript.textContent

var Media = paciente.querySelector('.info-imc')
var NotaMedia = parseInt(Media.textContent)

var valorIMC = parseInt(peso / altura*2)
console.log (valorIMC)
